#server:
#  port: 1001
#spring:
#  application:
#    name: gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        username: nacos
#        password: nacos
#        namespace: 175061a2-e062-456d-b4dc-e7e00c3a707b
#        group: DEFAULT_GROUP
#    gateway:
#      #配置动态路由
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#  rabbitmq:
#    host: 127.0.0.1
#    username: nacos
#    password: nacos
#    port: 5672
#    virtual-host: /power-shop
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
#    database: 0
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'